### ISSUE TITLE
Have you made any progress?

### ISSUE THREAD

**Issue by nicoschtein** [elliotwoods/ofxArUco#1]
Hi !
I was wondering if you ever finished making this addon with ArUco 3.x, I've been using https://github.com/frauzufall/ofxAruco and https://github.com/arturoc/ofxAruco which use 1.x, but I'd love to move to 3.x
Thanks in advance!

**Comment by elliotwoods** [comment]
https://github.com/elliotwoods/ofxArUco/tree/3.0.1
Like this?

**Comment by nicoschtein** [comment]
Yeah I saque you added the 3.0.1 lib but the addon itself is empty,
https://github.com/elliotwoods/ofxArUco/blob/3.0.1/src/ofxAruco.cpp
Right ?

Thanks again

**Comment by elliotwoods** [comment]
Yes i personally find there's no need to wrap the addon with code interfaces.
I just like to have the addon to keep the libs and compile settings wrapped up
You can see examples of how I use ofxArUco at:
https://github.com/elliotwoods/ofxRulr/tree/master/Plugin_ArUco/src/ofxRulr/Nodes/ArUco 

These are nodes for Rulr
You can see how with ofxCvMin (or ofxCv if you prefer) you can use ArUco directly without needing a wrapper.

**Comment by elliotwoods** [comment]
I can imagine if your main use of ArUco is the standard AR 'overlay 3d objects onto camera feed', then it would make sense to make oF wrappers.
But mostly I'm just using it for measuring things and calibrating cameras. So having access to the latest ArUco directly is the main aim.
Sorry if this doesn't match up with your usage.

**Comment by nicoschtein** [comment]
Oh I see, well actually I just wanted to get the position of the markers (center) projected to the camera or window 2D coordinate space, no AR / 3D needs, i just wanted to use the fast multiple fiducial marker detection of ArUco. So I'll take a look at your code, thanks !
